import { Sparkles } from 'lucide-react';

interface AIInterpretationProps {
  title?: string;
  content: string;
  variant?: 'info' | 'success' | 'warning';
}

export function AIInterpretation({ 
  title = "AI Clinical Interpretation", 
  content,
  variant = 'info'
}: AIInterpretationProps) {
  const variants = {
    info: {
      bg: 'bg-gradient-to-r from-purple-50 to-indigo-50',
      border: 'border-purple-200',
      titleColor: 'text-purple-900',
      textColor: 'text-purple-800',
      iconColor: 'text-purple-600',
      badgeBg: 'bg-purple-100',
      badgeText: 'text-purple-700'
    },
    success: {
      bg: 'bg-gradient-to-r from-emerald-50 to-teal-50',
      border: 'border-emerald-200',
      titleColor: 'text-emerald-900',
      textColor: 'text-emerald-800',
      iconColor: 'text-emerald-600',
      badgeBg: 'bg-emerald-100',
      badgeText: 'text-emerald-700'
    },
    warning: {
      bg: 'bg-gradient-to-r from-amber-50 to-orange-50',
      border: 'border-amber-200',
      titleColor: 'text-amber-900',
      textColor: 'text-amber-800',
      iconColor: 'text-amber-600',
      badgeBg: 'bg-amber-100',
      badgeText: 'text-amber-700'
    }
  };

  const style = variants[variant];

  return (
    <div className={`${style.bg} border ${style.border} rounded-lg p-4 shadow-sm`}>
      <div className="flex items-start gap-3">
        <div className={`mt-0.5 ${style.iconColor}`}>
          <Sparkles className="w-5 h-5" />
        </div>
        <div className="flex-1">
          <div className="flex items-center gap-2 mb-2">
            <h4 className={`text-sm ${style.titleColor}`}>{title}</h4>
            <span className={`px-2 py-0.5 ${style.badgeBg} ${style.badgeText} rounded text-xs`}>
              AI-Generated
            </span>
          </div>
          <p className={`text-sm ${style.textColor} leading-relaxed`}>
            {content}
          </p>
          <p className="text-xs text-gray-500 mt-2 italic">
            This interpretation is generated by our intelligent clinical decision support system. Always validate with clinical judgment.
          </p>
        </div>
      </div>
    </div>
  );
}
